[package]
name = "quazilang"
version = "26.0.1"
edition = "2024"
license = "0BSD"
description = "Quazi programming language bootstrap"

[[bin]]
name = "qz"
path = "src/main.rs"

[dependencies]
clap      = { version = "4.6.1", features = ["derive"] }
serde     = { version = "1.0",   features = ["derive"] }
toml      = "0.8"
object    = { version = "0.36",  features = ["write"] }
iced-x86  = { version = "1",     features = ["code_asm"] }
tower-lsp = "0.20"
tokio     = { version = "1", features = ["rt-multi-thread", "io-std", "io-util", "sync"] }
