name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: codeberg-medium
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v3

      - name: Cache cargo
        uses: https://code.forgejo.org/actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-

      - name: Install Rust stable
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run tests
        run: cargo test

  build:
    name: Build release binary
    runs-on: codeberg-medium
    needs: test
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v3

      - name: Cache cargo
        uses: https://code.forgejo.org/actions/cache@v3
        
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-

      - name: Install Rust stable
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: https://code.forgejo.org/actions/upload-artifact@v3
        with:
          name: void-linux-x86_64
          path: target/release/void