[package]
name = "http-client-server"
version = "0.1.0"
out_dir = "build"

[[bin]]
name = "http-client-server"
path = "src/main.qz"

[[bin]]
name = "http-server"
path = "src/server.qz"

[[bin]]
name = "http-client"
path = "src/client.qz"

[target.x86_64-linux.link]
libc = true
