// Quazi Programming Language
// Copyright (c) 2026 quazilang
// SPDX-License-Identifier: 0BSD

use std::collections::{HashMap, HashSet};

use crate::cli::HeaderTarget;
use crate::parser::ast::{AttrArg, AttrVal, Attribute, ItemKind, Program, Type, TypeKind};

#[derive(Clone)]
struct Aggregate<'a> {
    name: &'a str,
    fields: &'a [(String, Type, bool)],
    bit_widths: &'a [Option<u8>],
    is_union: bool,
    attributes: &'a [Attribute],
}

#[derive(Clone)]
struct Alias<'a> {
    name: &'a str,
    ty: &'a TypeKind,
    attributes: &'a [Attribute],
    public: bool,
}

struct HeaderContext<'a> {
    target: HeaderTarget,
    aliases: HashMap<&'a str, Alias<'a>>,
    aggregates: HashMap<&'a str, Aggregate<'a>>,
}

pub fn generate(
    program: &Program,
    library_ranges: &[std::ops::Range<usize>],
    target: HeaderTarget,
    guard: &str,
) -> Result<String, Vec<String>> {
    let is_library = |start| library_ranges.iter().any(|range| range.contains(&start));
    let mut aliases = HashMap::new();
    let mut aggregates = HashMap::new();

    for item in &program.items {
        match &item.node {
            ItemKind::TypeAlias {
                name,
                generic_params,
                aliased_type,
                attributes,
                public,
            } if generic_params.is_empty() && cfg_active(attributes, target) => {
                aliases.insert(
                    name.as_str(),
                    Alias {
                        name,
                        ty: &aliased_type.node,
                        attributes,
                        public: *public && !is_library(item.span.start),
                    },
                );
            }
            ItemKind::Struct {
                name,
                generic_params,
                fields,
                bit_widths,
                is_union,
                attributes,
                public: _,
            } if generic_params.is_empty() && cfg_active(attributes, target) => {
                aggregates.insert(
                    name.as_str(),
                    Aggregate {
                        name,
                        fields,
                        bit_widths,
                        is_union: *is_union,
                        attributes,
                    },
                );
            }
            _ => {}
        }
    }

    let context = HeaderContext {
        target,
        aliases,
        aggregates,
    };
    let mut required = HashSet::new();
    for item in &program.items {
        if is_library(item.span.start) {
            continue;
        }
        match &item.node {
            ItemKind::Fn {
                params,
                return_ty,
                attributes,
                ..
            } if cfg_active(attributes, target)
                && attributes
                    .iter()
                    .any(|attribute| attribute.name == "export") =>
            {
                for param in params {
                    collect_named_types(&param.ty.node, &mut required);
                }
                collect_named_types(&return_ty.node, &mut required);
            }
            ItemKind::TypeAlias {
                name,
                public: true,
                attributes,
                ..
            } if cfg_active(attributes, target) && has_repr_c(attributes) => {
                required.insert(name.clone());
            }
            ItemKind::Struct {
                name,
                public: true,
                attributes,
                ..
            } if cfg_active(attributes, target)
                && (has_repr_c(attributes) || has_opaque(attributes)) =>
            {
                required.insert(name.clone());
            }
            _ => {}
        }
    }
    expand_required_types(&context, &mut required);

    let mut errors = Vec::new();
    let guard = sanitize_guard(guard);
    let target_name = match target {
        HeaderTarget::X86_64Linux => "x86_64-linux",
        HeaderTarget::X86_64Windows => "x86_64-windows",
    };
    let mut out = format!(
        "/* Generated by qz header for {target_name}. Do not edit. */\n\
         #ifndef {guard}\n#define {guard}\n\n\
         #include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n\n\
         #ifdef __cplusplus\nextern \"C\" {{\n#endif\n\n"
    );

    let mut aggregate_names: Vec<_> = context
        .aggregates
        .values()
        .filter(|aggregate| required.contains(aggregate.name))
        .cloned()
        .collect();
    aggregate_names.sort_by_key(|aggregate| aggregate.name);
    for aggregate in &aggregate_names {
        let kind = if aggregate.is_union {
            "union"
        } else {
            "struct"
        };
        out.push_str(&format!(
            "typedef {kind} {} {};\n",
            aggregate.name, aggregate.name
        ));
    }
    if !aggregate_names.is_empty() {
        out.push('\n');
    }

    let mut alias_names: Vec<_> = context
        .aliases
        .values()
        .filter(|alias| required.contains(alias.name))
        .cloned()
        .collect();
    alias_names.sort_by_key(|alias| alias.name);
    for alias in &alias_names {
        if has_repr_c(alias.attributes) {
            let TypeKind::Fn { params, return_ty } = alias.ty else {
                continue;
            };
            match callback_typedef(alias.name, params, &return_ty.node, &context) {
                Ok(declaration) => out.push_str(&declaration),
                Err(error) => errors.push(error),
            }
        } else if alias.public {
            match declaration(alias.ty, alias.name, &context) {
                Ok(declaration) => out.push_str(&format!("typedef {declaration};\n")),
                Err(error) => errors.push(error),
            }
        }
    }
    if !alias_names.is_empty() {
        out.push('\n');
    }

    for aggregate in &aggregate_names {
        if has_opaque(aggregate.attributes) {
            continue;
        }
        if !has_repr_c(aggregate.attributes) {
            errors.push(format!(
                "type `{}` is used by the C API but is not @repr(C) or @opaque",
                aggregate.name
            ));
            continue;
        }
        emit_aggregate(&mut out, aggregate, &context, &mut errors);
    }

    for item in &program.items {
        let ItemKind::Fn {
            name,
            params,
            return_ty,
            attributes,
            c_variadic,
            ..
        } = &item.node
        else {
            continue;
        };
        if is_library(item.span.start)
            || !cfg_active(attributes, target)
            || !attributes
                .iter()
                .any(|attribute| attribute.name == "export")
        {
            continue;
        }
        let symbol = export_symbol(attributes).unwrap_or_else(|| name.clone());
        if !is_c_identifier(&symbol) {
            errors.push(format!(
                "export symbol `{symbol}` is not a valid C identifier for header generation"
            ));
            continue;
        }
        let return_type = match c_base_type(&return_ty.node, &context, &mut HashSet::new()) {
            Ok(ty) => ty,
            Err(error) => {
                errors.push(format!("export `{symbol}` return type: {error}"));
                continue;
            }
        };
        let mut rendered = Vec::new();
        for param in params {
            match declaration(&param.ty.node, &param.name, &context) {
                Ok(param) => rendered.push(param),
                Err(error) => errors.push(format!("export `{symbol}` parameter: {error}")),
            }
        }
        if *c_variadic {
            rendered.push("...".to_string());
        }
        if rendered.is_empty() {
            rendered.push("void".to_string());
        }
        out.push_str(&format!(
            "{return_type} {symbol}({});\n",
            rendered.join(", ")
        ));
    }

    out.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n#endif\n");
    if errors.is_empty() {
        Ok(out)
    } else {
        Err(errors)
    }
}

fn emit_aggregate(
    out: &mut String,
    aggregate: &Aggregate<'_>,
    context: &HeaderContext<'_>,
    errors: &mut Vec<String>,
) {
    let kind = if aggregate.is_union {
        "union"
    } else {
        "struct"
    };
    let packed = repr_packed(aggregate.attributes);
    let alignment = repr_alignment(aggregate.attributes);
    if packed && context.target == HeaderTarget::X86_64Windows {
        out.push_str("#pragma pack(push, 1)\n");
    }
    let modifier = match context.target {
        HeaderTarget::X86_64Linux => {
            let mut values = Vec::new();
            if packed {
                values.push("packed".to_string());
            }
            if let Some(alignment) = alignment {
                values.push(format!("aligned({alignment})"));
            }
            if values.is_empty() {
                String::new()
            } else {
                format!(" __attribute__(({}))", values.join(", "))
            }
        }
        HeaderTarget::X86_64Windows => alignment
            .map(|alignment| format!(" __declspec(align({alignment}))"))
            .unwrap_or_default(),
    };
    out.push_str(&format!("{kind}{modifier} {} {{\n", aggregate.name));
    for (index, (name, ty, _)) in aggregate.fields.iter().enumerate() {
        match declaration(&ty.node, name, context) {
            Ok(mut field) => {
                if let Some(width) = aggregate.bit_widths.get(index).copied().flatten() {
                    field.push_str(&format!(" : {width}"));
                }
                out.push_str(&format!("    {field};\n"));
            }
            Err(error) => errors.push(format!(
                "field `{}.{name}` cannot be written to C: {error}",
                aggregate.name
            )),
        }
    }
    out.push_str("};\n");
    if packed && context.target == HeaderTarget::X86_64Windows {
        out.push_str("#pragma pack(pop)\n");
    }
    out.push('\n');
}

fn callback_typedef(
    name: &str,
    params: &[Type],
    return_ty: &TypeKind,
    context: &HeaderContext<'_>,
) -> Result<String, String> {
    let return_type = c_base_type(return_ty, context, &mut HashSet::new())?;
    let rendered = if params.is_empty() {
        "void".to_string()
    } else {
        params
            .iter()
            .map(|param| c_base_type(&param.node, context, &mut HashSet::new()))
            .collect::<Result<Vec<_>, _>>()?
            .join(", ")
    };
    Ok(format!("typedef {return_type} (*{name})({rendered});\n"))
}

fn declaration(ty: &TypeKind, name: &str, context: &HeaderContext<'_>) -> Result<String, String> {
    match ty {
        TypeKind::Array { elem_ty, len } => Ok(format!(
            "{} {name}[{len}]",
            c_base_type(&elem_ty.node, context, &mut HashSet::new())?
        )),
        TypeKind::FlexibleArray { elem_ty } => Ok(format!(
            "{} {name}[]",
            c_base_type(&elem_ty.node, context, &mut HashSet::new())?
        )),
        _ => Ok(format!(
            "{} {name}",
            c_base_type(ty, context, &mut HashSet::new())?
        )),
    }
}

fn c_base_type(
    ty: &TypeKind,
    context: &HeaderContext<'_>,
    resolving: &mut HashSet<String>,
) -> Result<String, String> {
    let primitive = match ty {
        TypeKind::Int8 => Some("int8_t"),
        TypeKind::Int16 => Some("int16_t"),
        TypeKind::Int32 => Some("int32_t"),
        TypeKind::Int64 => Some("int64_t"),
        TypeKind::Uint8 => Some("uint8_t"),
        TypeKind::Uint16 => Some("uint16_t"),
        TypeKind::Uint32 => Some("uint32_t"),
        TypeKind::Uint64 => Some("uint64_t"),
        TypeKind::Isize => Some("intptr_t"),
        TypeKind::Usize => Some("uintptr_t"),
        TypeKind::Float32 => Some("float"),
        TypeKind::Float64 => Some("double"),
        TypeKind::Bool => Some("bool"),
        TypeKind::Void => Some("void"),
        _ => None,
    };
    if let Some(primitive) = primitive {
        return Ok(primitive.to_string());
    }
    match ty {
        TypeKind::RawPtr { inner } => Ok(format!(
            "{} *",
            c_base_type(&inner.node, context, resolving)?
        )),
        TypeKind::Named { name, type_args } if type_args.is_empty() => {
            if name == "c_long" {
                return Ok(match context.target {
                    HeaderTarget::X86_64Linux => "int64_t",
                    HeaderTarget::X86_64Windows => "int32_t",
                }
                .to_string());
            }
            if name == "c_ulong" {
                return Ok(match context.target {
                    HeaderTarget::X86_64Linux => "uint64_t",
                    HeaderTarget::X86_64Windows => "uint32_t",
                }
                .to_string());
            }
            if context.aggregates.contains_key(name.as_str())
                || context
                    .aliases
                    .get(name.as_str())
                    .is_some_and(|alias| has_repr_c(alias.attributes))
            {
                return Ok(name.clone());
            }
            let Some(alias) = context.aliases.get(name.as_str()) else {
                return Err(format!("unsupported named type `{name}`"));
            };
            if !resolving.insert(name.clone()) {
                return Err(format!("cyclic type alias `{name}`"));
            }
            let result = c_base_type(alias.ty, context, resolving);
            resolving.remove(name);
            result
        }
        TypeKind::Array { .. } | TypeKind::FlexibleArray { .. } => {
            Err("array type requires a declarator".to_string())
        }
        other => Err(format!("unsupported C header type `{other}`")),
    }
}

fn collect_named_types(ty: &TypeKind, names: &mut HashSet<String>) {
    match ty {
        TypeKind::Named { name, type_args } => {
            names.insert(name.clone());
            for argument in type_args {
                collect_named_types(&argument.node, names);
            }
        }
        TypeKind::RawPtr { inner }
        | TypeKind::Ref { inner }
        | TypeKind::Array { elem_ty: inner, .. }
        | TypeKind::FlexibleArray { elem_ty: inner }
        | TypeKind::Slice { elem_ty: inner } => collect_named_types(&inner.node, names),
        TypeKind::Fn { params, return_ty } | TypeKind::CFn { params, return_ty } => {
            for param in params {
                collect_named_types(&param.node, names);
            }
            collect_named_types(&return_ty.node, names);
        }
        _ => {}
    }
}

fn expand_required_types(context: &HeaderContext<'_>, required: &mut HashSet<String>) {
    loop {
        let before = required.len();
        for name in required.clone() {
            if let Some(alias) = context.aliases.get(name.as_str()) {
                collect_named_types(alias.ty, required);
            }
            if let Some(aggregate) = context.aggregates.get(name.as_str()) {
                for (_, ty, _) in aggregate.fields {
                    collect_named_types(&ty.node, required);
                }
            }
        }
        if required.len() == before {
            break;
        }
    }
}

fn has_repr_c(attributes: &[Attribute]) -> bool {
    attributes.iter().any(|attribute| {
        attribute.name == "repr"
            && matches!(
                attribute.args.first(),
                Some(AttrArg::Positional(AttrVal::Ident(value))) if value == "C"
            )
    })
}

fn has_opaque(attributes: &[Attribute]) -> bool {
    attributes
        .iter()
        .any(|attribute| attribute.name == "opaque")
}

fn repr_packed(attributes: &[Attribute]) -> bool {
    attributes.iter().any(|attribute| {
        attribute.name == "repr"
            && attribute.args.iter().any(|argument| {
                matches!(argument, AttrArg::Positional(AttrVal::Ident(value)) if value == "packed")
            })
    })
}

fn repr_alignment(attributes: &[Attribute]) -> Option<i64> {
    attributes
        .iter()
        .find(|attribute| attribute.name == "repr")
        .and_then(|attribute| {
            attribute.args.iter().find_map(|argument| match argument {
                AttrArg::KeyValue(key, AttrVal::Int(value)) if key == "align" => Some(*value),
                _ => None,
            })
        })
}

fn export_symbol(attributes: &[Attribute]) -> Option<String> {
    attributes
        .iter()
        .find(|attribute| attribute.name == "export")
        .and_then(|attribute| attribute.args.first())
        .and_then(|argument| match argument {
            AttrArg::Positional(AttrVal::Str(symbol)) => Some(symbol.clone()),
            _ => None,
        })
}

fn cfg_active(attributes: &[Attribute], target: HeaderTarget) -> bool {
    attributes
        .iter()
        .filter(|attribute| attribute.name == "cfg")
        .all(|attribute| {
            attribute.args.iter().all(|argument| match argument {
                AttrArg::KeyValue(key, AttrVal::Str(value))
                | AttrArg::KeyValue(key, AttrVal::Ident(value)) => match key.as_str() {
                    "target_os" => match target {
                        HeaderTarget::X86_64Linux => value == "linux",
                        HeaderTarget::X86_64Windows => value == "windows",
                    },
                    "target_arch" => value == "x86_64",
                    "target_abi" => match target {
                        HeaderTarget::X86_64Linux => value == "sysv",
                        HeaderTarget::X86_64Windows => value == "win64",
                    },
                    _ => false,
                },
                _ => false,
            })
        })
}

fn sanitize_guard(value: &str) -> String {
    let mut result: String = value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if result.is_empty() || result.as_bytes()[0].is_ascii_digit() {
        result.insert_str(0, "QZ_");
    }
    if !result.ends_with("_H") {
        result.push_str("_H");
    }
    result
}

fn is_c_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
        && chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn parse(source: &str) -> Program {
        Parser::new(Lexer::new(source).tokenize()).parse().unwrap()
    }

    #[test]
    fn emits_aggregates_callbacks_bitfields_flexible_arrays_and_exports() {
        let program = parse(
            r#"
@repr(C, packed, align=8) pub struct Packet {
    flags: u32:5,
    data: [u8; ..],
}
@repr(C) pub union Value { integer: i64, decimal: f64 }
@repr(C) pub type Callback = fn(*Packet, Value) i32;
@export("quazi_visit") pub unsafe fn visit(callback: Callback, packet: *Packet) i32 { ret 0; }
"#,
        );
        let header = generate(&program, &[], HeaderTarget::X86_64Linux, "quazi_api.h").unwrap();
        assert!(header.contains("typedef struct Packet Packet;"));
        assert!(header.contains("__attribute__((packed, aligned(8)))"));
        assert!(header.contains("uint32_t flags : 5;"));
        assert!(header.contains("uint8_t data[];"));
        assert!(header.contains("typedef int32_t (*Callback)(Packet *, Value);"));
        assert!(header.contains("int32_t quazi_visit(Callback callback, Packet * packet);"));
        assert!(header.contains("extern \"C\""));
    }

    #[test]
    fn selects_target_cfg_and_c_long_width() {
        let program = parse(
            r#"
@cfg(target_os="linux") pub type platform_word = i64;
@cfg(target_os="windows") pub type platform_word = i32;
@export pub fn width(value: c_long) platform_word { ret value; }
"#,
        );
        let linux = generate(&program, &[], HeaderTarget::X86_64Linux, "api.h").unwrap();
        let windows = generate(&program, &[], HeaderTarget::X86_64Windows, "api.h").unwrap();
        assert!(linux.contains("int64_t width(int64_t value);"));
        assert!(windows.contains("int32_t width(int32_t value);"));
    }

    #[test]
    fn rejects_non_c_aggregate_dependencies() {
        let program = parse(
            r#"
struct Internal { value: i32 }
@export pub fn expose(value: Internal) Internal { ret value; }
"#,
        );
        let errors = generate(&program, &[], HeaderTarget::X86_64Linux, "api.h").unwrap_err();
        assert!(errors.iter().any(|error| {
            error.contains("type `Internal` is used by the C API but is not @repr(C) or @opaque")
        }));
    }

    #[test]
    fn spells_windows_packing_and_alignment() {
        let program = parse(
            r#"
@repr(C, packed, align=16) pub struct Packet { value: i32 }
"#,
        );
        let header = generate(&program, &[], HeaderTarget::X86_64Windows, "api.h").unwrap();
        assert!(header.contains("#pragma pack(push, 1)"));
        assert!(header.contains("struct __declspec(align(16)) Packet"));
        assert!(header.contains("#pragma pack(pop)"));
    }

    #[test]
    fn ignores_unrelated_public_quazi_types() {
        let program = parse(
            r#"
pub struct QuaziOnly { text: str }
pub type AlsoQuaziOnly = str;
@export pub fn answer() i32 { ret 42; }
"#,
        );
        let header = generate(&program, &[], HeaderTarget::X86_64Linux, "api.h").unwrap();
        assert!(header.contains("int32_t answer(void);"));
        assert!(!header.contains("QuaziOnly"));
        assert!(!header.contains("AlsoQuaziOnly"));
    }
}
